In [1]:
from sklearn.metrics.pairwise import euclidean_distances

In [6]:
X = [[0, 1,1], [1, 1,2], [2,3,1] ,[3,1,2] ]

In [43]:
y=euclidean_distances(X, X)

In [44]:

print(y.T)

[[0.         1.41421356 2.82842712 3.16227766]
 [1.41421356 0.         2.44948974 2.        ]
 [2.82842712 2.44948974 0.         2.44948974]
 [3.16227766 2.         2.44948974 0.        ]]


In [45]:
import numpy as np

In [23]:
print(c)

[0.         1.41421356 2.         2.44948974]


In [54]:
c=y[:][2]
d=np.sort(y[:][2])

In [55]:
print(c)

[2.82842712 2.44948974 0.         2.44948974]


In [40]:
print(e)

[0.         1.41421356 2.         2.44948974 0.         2.44948974
 2.44948974 2.82842712]
