In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [4]:
house=pd.read_csv('/home/rana/Documents/housing.csv')
X=house.iloc[:,:-1].values
Y=house.iloc[:,1].values
house.head()

Unnamed: 1
0  0.951        30.0
1  1.036        39.9
2  0.676        46.5
3  1.456        48.6
4  1.186        51.5

In [6]:
from sklearn.model_selection import train_test_split

In [8]:
x_train,x_test,y_train,y_test = train_test_split(X,Y,test_size=0.2,random_state=0)

In [9]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [11]:
y_pred=regressor.predict(x_test)
print(y_pred)

[ 125.28879563  152.1148754   165.96624993   97.41071273   80.3448842
   41.30387921  145.74441201  120.90544926   80.3448842   133.99704375
   71.11063452   84.202229  ]


In [12]:
print(regressor.coef_)

[ 58.44461825]


In [13]:
print(regressor.intercept_)

1.79531727608


In [17]:
from sklearn.metrics import r2_score
r2_score(y_test,y_pred)

0.67806251687702224

In [21]:
y_test

array([ 122.9 ,  119.9 ,  135.9 ,  106.  ,   79.  ,   46.5 ,  119.9 ,
        144.9 ,   95.8 ,  152.55,   51.5 ,   76.9 ])

In [19]:
y_pred

array([ 125.28879563,  152.1148754 ,  165.96624993,   97.41071273,
         80.3448842 ,   41.30387921,  145.74441201,  120.90544926,
         80.3448842 ,  133.99704375,   71.11063452,   84.202229  ])

In [22]:
print(y_test)
print(x_test)
print(y_train)
print(x_train)

[ 122.9   119.9   135.9   106.     79.     46.5   119.9   144.9    95.8
  152.55   51.5    76.9 ]
[[ 2.113]
 [ 2.572]
 [ 2.809]
 [ 1.636]
 [ 1.344]
 [ 0.676]
 [ 2.463]
 [ 2.038]
 [ 1.344]
 [ 2.262]
 [ 1.186]
 [ 1.41 ]]
[ 109.9    132.9    114.9    134.9    124.9     62.5     82.9    112.29
  108.9    189.5    169.9     89.9    179.     102.      84.9     56.99
  110.      85.     156.9     93.5    164.      65.5     79.95    99.9
   87.9    139.5    147.6    167.5    126.9     39.9     79.9    199.
   99.5     59.9     98.5    123.938   94.9     89.9     69.     129.9
  179.9     48.6     30.     175.     149.99   139.99 ]
[[ 1.8  ]
 [ 1.98 ]
 [ 2.082]
 [ 2.483]
 [ 1.852]
 [ 0.994]
 [ 1.524]
 [ 1.387]
 [ 1.5  ]
 [ 2.51 ]
 [ 2.949]
 [ 1.624]
 [ 2.805]
 [ 1.312]
 [ 1.75 ]
 [ 1.456]
 [ 1.972]
 [ 1.152]
 [ 2.456]
 [ 1.532]
 [ 2.436]
 [ 1.176]
 [ 1.77 ]
 [ 1.45 ]
 [ 1.77 ]
 [ 2.036]
 [ 2.37 ]
 [ 1.92 ]
 [ 2.67 ]
 [ 1.036]
 [ 1.064]
 [ 3.627]
 [ 1.752]
 [ 1.368]
 [ 1.55 ]
 [ 2.016]
 [ 1.647]